name = "devhub"
default_domain = "devhub"

[constants]
version = 4.0
package-name-org = "mongodb-org"
pgp-version = "{+version+}"

[page_groups]
"Java Tutorials" = ["/quickstart/java-setup-crud-operations", "/quickstart/java-mapping-pojos", "/quickstart/java-aggregation-pipeline", "/quickstart/java-change-streams"]
"BSON Tutorials" = ["/quickstart/bson-data-types-decimal128", "/quickstart/bson-data-types-objectid"]